<a href="https://colab.research.google.com/github/ameyanjarlekar/MRT/blob/master/basicbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! git clone https://github.com/ameyanjarlekar/MRT

Cloning into 'MRT'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 44 (delta 16), reused 13 (delta 3), pack-reused 0
Unpacking objects: 100% (44/44), done.


In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [14]:
import numpy as np
new=np.load("gdrive/My Drive/outputfinalgrey.npy")
newa = np.load("MRT/outputfinalgreyans.npy")
rng_state = np.random.get_state()
np.random.shuffle(new)
np.random.set_state(rng_state)
np.random.shuffle(newa)
#newa = np.array( [[1,0]]*27600 + [[0,1]]*88784)
#sprint(len(a))


#outfile.seek(0)
#new = np.load(outfile)
#print(new.shape)
#outfileans.seek(0)
#newa = np.load(outfileans)
#print(newa.shape)
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, Dropout,Reshape
from keras import optimizers
model = Sequential()
model.add(Reshape((50,50,1), input_shape=(50,50)))
model.add(Conv2D(64,5,padding='same',input_shape=(50,50,1)))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2, padding='same'))
#model.add(Dropout(0.5))
model.add(Conv2D(64,5,padding='same'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2, padding='same'))
#model.add(Dropout(0.5))
model.add(Conv2D(64,5,padding='same'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2, padding='same'))
#model.add(Dropout(0.5))
model.add(Conv2D(64,5,padding='same'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2, padding='same'))
#model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(2))
model.add(keras.layers.Activation('softmax'))
sgd = optimizers.SGD(lr = 0.05, decay = 0.5)
model.compile(optimizer=sgd, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(new,newa,batch_size=1024,epochs=10,validation_split=0.2)

Train on 93107 samples, validate on 23277 samples
Epoch 1/10
93107/93107 [==============================] - 40s 425us/step - loss: 0.2850 - acc: 0.9060 - val_loss: 0.2130 - val_acc: 0.9201
Epoch 2/10
93107/93107 [==============================] - 36s 387us/step - loss: 0.2055 - acc: 0.9228 - val_loss: 0.2042 - val_acc: 0.9233
Epoch 3/10
93107/93107 [==============================] - 36s 386us/step - loss: 0.1995 - acc: 0.9249 - val_loss: 0.1989 - val_acc: 0.9246
Epoch 4/10
93107/93107 [==============================] - 36s 386us/step - loss: 0.1960 - acc: 0.9267 - val_loss: 0.1954 - val_acc: 0.9263
Epoch 5/10
93107/93107 [==============================] - 36s 386us/step - loss: 0.1936 - acc: 0.9276 - val_loss: 0.1928 - val_acc: 0.9279
Epoch 6/10
93107/93107 [==============================] - 36s 385us/step - loss: 0.1918 - acc: 0.9288 - val_loss: 0.1910 - val_acc: 0.9285
Epoch 7/10
93107/93107 [==============================] - 36s 386us/step - loss: 0.1904 - acc: 0.9295 - val_loss: 0.

In [6]:
import numpy as np
new=np.load("gdrive/My Drive/outputfinalgrey.npy")
print(new[1])

[[121 115 105 ...  96  96  95]
 [117 116 102 ...  96  97  98]
 [114 107  96 ... 102 101  98]
 ...
 [ 90  90  91 ...  93  96  96]
 [ 91  93  93 ...  95  96  95]
 [ 93  96  94 ...  97  96  94]]


In [7]:
import numpy as np
new=np.load("gdrive/My Drive/outputfinal.npy")
print(new[1])

[[[ 39 106 184]
  [ 33  97 182]
  [ 27  90 166]
  ...
  [ 29  78 160]
  [ 30  78 157]
  [ 29  79 154]]

 [[ 38  99 183]
  [ 32 101 179]
  [ 25  86 163]
  ...
  [ 30  75 164]
  [ 30  80 159]
  [ 30  83 155]]

 [[ 32  96 182]
  [ 29  89 175]
  [ 27  77 161]
  ...
  [ 30  84 167]
  [ 31  85 161]
  [ 30  83 155]]

 ...

 [[ 26  76 145]
  [ 26  75 144]
  [ 25  77 145]
  ...
  [ 29  75 156]
  [ 30  79 155]
  [ 28  80 154]]

 [[ 27  75 148]
  [ 25  78 150]
  [ 24  79 150]
  ...
  [ 28  79 152]
  [ 30  82 152]
  [ 27  81 151]]

 [[ 28  78 148]
  [ 25  83 149]
  [ 22  80 149]
  ...
  [ 28  80 158]
  [ 29  80 154]
  [ 27  80 150]]]
